apiVersion: v1
kind: Secret
metadata:
  name: ghost-on-kubernetes-mysql-env
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes-mysql
    app.kubernetes.io/name: ghost-on-kubernetes-mysql-env
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: ghost-on-kubernetes
    
type: Opaque
stringData:
  MYSQL_DATABASE: mysql-db-name # test
  MYSQL_USER: mysql-db-user 
  MYSQL_PASSWORD: mysql-db-password 
  MYSQL_ROOT_PASSWORD: mysql-db-root-password 
  MYSQL_HOST: '%' 
