apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrss
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttrss
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      containers:
      - name: ttrss
        image: blacs30/tt-rss-docker:latest
        env:
        - name: DB_TYPE
          value: pgsql
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: ttrss
        - name: DB_USER
          value: ttrss
        - name: DB_PASS
          value: ttrsspassword
        - name: ENABLE_PLUGINS
          value: auth_internal, note
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/www/html
          name: ttrss-data
      volumes:
      - name: ttrss-data
        persistentVolumeClaim:
          claimName: ttrss-pvc
