apiVersion: v1
kind: Service
metadata:
  name: ttrss
  namespace: applications
spec:
  selector:
    app: ttrss
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31582
  type: NodePort
