apiVersion: apps/v1
kind: Deployment
metadata:
  name: kicad
  namespace: applications
  labels:
    app: kicad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kicad
  template:
    metadata:
      labels:
        app: kicad
    spec:
      containers:
      - name: kicad
        image: lscr.io/linuxserver/kicad:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: kicad-config
          mountPath: "/config/k3s.yaml" 
        securityContext:
          seccompProfile:
            type: Unconfined
      volumes:
      - name: kicad-config
        hostPath:
          path: /etc/rancher/k3s/k3s.yaml  
  restartPolicy: Always  
