apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kicad-pvc
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: standard 
