apiVersion: v1
kind: Service
metadata:
  name: kicad-service
  namespace: applications
spec:
  selector:
    app: kicad
  ports:
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32006
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32007
  type: NodePort
