apiVersion: v1
kind: Service
metadata:
  name: kicad-service
  namespace: applications
spec:
  selector:
    app: kicad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32005
  type: NodePort
