apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: home-assistant
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: linuxserver/bookstack:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: "base64:qvU0FRPl0b2l+zJG91foLINkY79uF2XZVwUABUZOEbc="
        - name: APP_URL
          value: "http://100.104.171.102:31580"
        - name: DB_HOST
          value: "bookstack-db"
        - name: DB_USERNAME
          value: "bookstack_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: user-password
        - name: DB_DATABASE
          value: "bookstack"
        volumeMounts:
        - name: bookstack-data
          mountPath: /config
      volumes:
      - name: bookstack-data
        persistentVolumeClaim:
          claimName: bookstack-pvc
