apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: home-assistant
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: linuxserver/bookstack:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "bookstack-db"
        - name: DB_USER
          value: "bookstack_user"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: password
        - name: DB_DATABASE
          value: "bookstack"
        volumeMounts:
        - name: bookstack-data
          mountPath: /config
      volumes:
      - name: bookstack-data
        persistentVolumeClaim:
          claimName: bookstack-pvc
