apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-db
  namespace: home-assistant
  labels:
    app: bookstack-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-db
  template:
    metadata:
      labels:
        app: bookstack-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "bookstack"
        - name: MYSQL_USER
          value: "bookstack_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: password
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: bookstack-db-pvc
