apiVersion: v1
kind: Service
metadata:
  name: bookstack
  namespace: home-assistant
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 
  selector:
    app: bookstack
  type: NodePort
