apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: tools
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    log_dest stdout
    persistence true
    persistence_location /mosquitto/data/
