apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: tools
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          name: mosquitto-config
        - mountPath: /mosquitto/data
          name: mosquitto-data
        - mountPath: /mosquitto/log
          name: mosquitto-logs
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data-pvc
      - name: mosquitto-logs
        emptyDir: {}
