apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pv-claim
  namespace: tools
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 