apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password
  namespace: tools
  labels:
    app: mosquitto
type: Opaque
data:
  password.txt: admin:$7$101$tz6arXoVTIHSiOis$msNpyhYVntBTDtPjHeUhr8YAckwsKfQRivH9hm+It7Bn3/1OB2aBHQq+S0n5AZMokqRtv79Rzh5oZMwnnhtXZw==
