apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: tools
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
  type: LoadBalancer 
