apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  config.php: |
    <?php
    $CONFIG = array (
      'htaccess.RewriteBase' => '/',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'apps_paths' =>
      array (
        0 =>
        array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 =>
        array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),
      'upgrade.disable-web' => true,
      'passwordsalt' => 'Eq2JBUL1QO+tLUU5AK4o51ndKOIYQC',
      'secret' => 'FBRoT0rupSNffKku7l0pNOdqypOiHvFOHYimp2sZVgS2Krlk',
      'trusted_domains' =>
      array (
        0 => 'localhost',
        1 => '100.104.171.102',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'sqlite3',
      'version' => '30.0.5.1',
      'overwrite.cli.url' => 'http://localhost',
      'dbname' => 'nextcloud',
      'installed' => true,
      'instanceid' => 'ocbfkf401yqt',
    );
