apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: applications
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: onerahmet/openai-whisper-asr-webservice:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /tmp # Mount for temporary audio file storage
          name: whisper-tmp
      volumes:
      - name: whisper-tmp
        emptyDir: {}
