apiVersion: v1
kind: Service
metadata:
  name: whisper-service
  namespace: applications
  labels:
    app: whisper
spec:
  type: NodePort
  selector:
    app: whisper
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
    NodePort: 32003
