apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: vaultwarden-cert
          mountPath: /ssl
          subPath: tls.crt
        - name: vaultwarden-cert
          mountPath: /ssl/tls.key
          subPath: tls.key
        - mountPath: /data
          name: vaultwarden-data
        env:
        - name: ROCKET_TLS
          value: '{"certs":"/ssl/tls.crt","key":"/ssl/tls.key"}'
      volumes:
      - name: vaultwarden-cert
        secret:
          secretName: vaultwarden-cert
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
