apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsshub
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsshub
  template:
    metadata:
      labels:
        app: rsshub
    spec:
      containers:
      - name: rsshub
        image: diygod/rsshub:latest
        env:
        - name: CACHE_TYPE
          value: redis
        - name: REDIS_URL
          value: redis://redis:6379
        ports:
        - containerPort: 1200
