apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: default
data:
  conf.yml: |
    pageInfo:
      title: pandaserver
      description: this is pandamonium!
      navLinks:
      - title: GitHub
        path: https://github.com/Lissy93/dashy

    appConfig:
      theme: colorful
      statusCheck: true

    sections:
    - name: apps
      icon: fas fa-traffic-light
      items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: hello-world
        description: hello-world test page
        url: http://100.104.171.102:31591/
        icon: favicon
      - title: bookstack
        description: bookstack app
        url: http://100.104.171.102:31580/
        icon: favicon
      - title: vaultwarden
        description: vaultwarden app
        url: https://100.104.171.102:30443/

