apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: default
data:
  conf.yml: |
    pageInfo:
      title: pandaserver
      description: this is pandamonium!
      navLinks:
      - title: GitHub
        path: https://github.com/Lissy93/dashy

    appConfig:
      theme: colorful
      statusCheck: true

    sections:
    - name: apps
      icon: fas fa-traffic-light
      items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: hello-world
        description: hello-world test page
        url: http://100.104.171.102:31590/
        icon: fas fa-globe
      - title: bookstack
        description: bookstack app
        url: http://100.104.171.102:31580/
        icon: fas fa-book
      - title: miniflux
        description: rss reader
        url: http://100.104.171.102:32004/
        icon: https://miniflux.app/favicon.ico
      - title: vaultwarden
        description: vaultwarden app
        url: https://100.104.171.102:30443/
        icon: fas fa-lock
    
    - name: tools
      icon: fas fa-tools
      items:
      - title: ollama
        description: connect via terminal
        url: http://100.104.171.102:32001/
        icon: https://ollama.com/public/ollama.png
      - title: node red
        description: Node Red app
        url: http://100.104.171.102:32002/
        icon: fas fa-screwdriver-wrench
      - title: kicad
        description: KICAD
        url: http://100.104.171.102:32010/
        icon: fas fa-atom
      - title: whisper
        description: Whisper app
        url: http://100.104.171.102:32003/
        icon: fas fa-microphone
      
    - name: quick access
      widgets:
      - type: clock
        options:
          timeZone: Europe/London
          format: en-GB
          hideDate: false
      - type: gl-network-interfaces
        options:
        hostname: http://192.168.130.2:61208


