apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: default
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          command:
            - "sh"
          args:
            - "-c"
            - |
              # Install Node.js v16
              curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
              apt-get install -y nodejs && \
              npm install && \
              npm run build --fix && \
              node server  
          volumeMounts:
            - mountPath: /app/config
              name: dashy-config
      volumes:
        - name: dashy-config
          configMap:
            name: dashy-config
---
