apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: default
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
            - name: DISABLE_ESLINT_PLUGIN
              value: "true"
          command:
            - "sh"
          args:
            - "-c"
            - |
              yarn build-and-start && \
              yarn build --fix && \
              node server
          volumeMounts:
            - mountPath: /app/config
              name: dashy-config
      volumes:
        - name: dashy-config
          configMap:
            name: dashy-config
