apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: default
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          command:
            - "sh"
          args:
            - "-c"
            - |
              # Install Node.js v16
              yarn run && \
              NODE_OPTIONS=--openssl-legacy-provider npm run --parallel build start --fix && \
              NODE_OPTIONS=--openssl-legacy-provider vue-cli-service build --fix && \
              node server  
          volumeMounts:
            - mountPath: /app/config
              name: dashy-config
      volumes:
        - name: dashy-config
          configMap:
            name: dashy-config
