apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: default
spec:
  selector:
    app: dashy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31592
  type: NodePort
