apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: applications
type: Opaque
data:
  POSTGRES_USER: bWluaWZsdXg=
  POSTGRES_PASSWORD: bWluaWZsdXhwYXNzd29yZA== 
  POSTGRES_DB: bWluaWZsdXg= 
