apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgres
  namespace: applications
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: miniflux-postgres
