apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: applications
spec:
  type: NodePort
  selector:
    app: vaultwarden
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
