apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: applications
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 11434
    nodePort: 32001
