apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: applications
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
          volumeMounts:
            - mountPath: /data
              name: nodered-data
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-pvc