apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: applications
  labels:
    app: nodered
spec:
  selector:
    app: nodered
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32002
  type: NodePort
