apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: applications
  labels:
    app: nodered
spec:
  type: NodePort
  selector:
    app: nodered
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32002
