apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secret
  namespace: applications
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9taW5pZmx1eDptaW5pZmx1eHBhc3N3b3JkQG1pbmlmbHV4LXBvc3RncmVzOjU0MzIvbWluaWZsdXg=
