apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_DB
          value: ttrss
        - name: POSTGRES_USER
          value: ttrss
        - name: POSTGRES_PASSWORD
          value: ttrsspassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
