apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    - op: add
      path: /spec/ignore
      value: 
        - "!nextcloud"
  target:
    kind: Kustomization
    name: flux-system
