apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    - op: add
      path: /spec/ignore
      value: 
        - "!nextcloud"
  target:
    kind: Kustomization
    name: flux-system
    namespace: flux-system
exclude:
- "clusters/default/nextcloud/values.yaml"
